version: "3.9"
services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: app
    ports:
      - "5000:8000"
    depends_on:
      - db
    
  db:
    image: mysql
    restart: always
    ports:
      - "8080:3306"
    volumes:
      - ./data:/data
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
    expose:
      - 3306