version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "5000:8000"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
    expose:
      - 3306