name: Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Cypress-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Cypress Unit Test
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Tags
        run: docker tag app ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Docker Images
        run: docker images

      - name: Docker Containers
        run: docker ps

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app:latest
